### ISSUE TITLE
Euchre: Suggestion for defending when holding left bower

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#34] opened 2022-03-19 16:34 UTC
From a customer:

> When defending and the bot defender holds the left bower and another small trump, the bot will, when able, trump small leaving the left bower alone. I've been playing Euchre for over 60 years and the first thing you learn is to never bare your left bower. You will surely lose it and that is what happens in your game. You get over trumped and out comes the right bower. When my bot partner bares the left bower and then loses it giving the opponents 2 or 4 points instead of 1, I want to teach the bot but there is no way to do it except to write you. This happens very frequently. The only time to trump small is when you are last to play to the trick.

**Comment by drittich** [comment] 2022-03-19 17:08
Duplicate of https://github.com/TricksterCards/TricksterBots/issues/30

**Comment by antross** [comment] 2022-03-22 02:08
Thanks for catching this @drittich!

**Closed by antross** 2022-03-22 02:08 UTC
Labels: duplicate, Euchre, card-play
