### ISSUE TITLE
500: Bot play without Joker and partner without Joker

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#262] opened 2024-06-18 16:08 UTC
> When a bot wins the bid but does not have the joker, it is understandable to have it play the lowest trump, but after the partner does not have the joker, the bot with the bid should play either the highest or next highest trump in their hand. They give up too many tricks if they keep playing the lowest trump.

**Comment by antross** [comment] 2024-10-23 17:30
Duplicate of #125

**Closed by antross** 2024-10-23 17:30 UTC
Labels: duplicate, customer, 500, card-play
