### ISSUE TITLE
500: Improve play against Open Misère

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#52] opened 2022-05-19 16:03 UTC
See screenshot below.

> Bot had winning hand but didn't play it.
> 
> Opposition went Open Misère, I had run out of clubs a lot earlier, the bot kept playing other suit and high cards, when Nora (bot) could have played the 9CL then 5CL to win, which was clear after I received the claim and the cards held are displayed. Note that although it looks like the bot couldn't get the lead, it had the lead many times and didn't play the winning cards.
> 
> The bots are terrible at misère, especially open misère, often playing suits that the opposition don't have when they had an alternative.

![image001](https://user-images.githubusercontent.com/4723541/169345904-dfc2a7aa-b1f2-49a5-b759-a117b1888037.png)

**Comment by johnson520** [comment] 2022-06-17 14:34
Customer provided this scenario he saw happen. "I" in this case is the player going Misère.

> Playing a misère hand, I led 6D, left seat 7D and right seat 5D – right seat LATER played Jack D which is the card that should have been discarded, preserving the 5…

**Comment by antross** [comment] 2023-01-29 18:36
Duplicate of #33

**Closed by antross** 2023-01-29 18:36 UTC
Labels: duplicate, customer, 500, card-play
